--DROP TABLE IF EXISTS real, synthetic

CREATE TABLE "real" (
    id SERIAL PRIMARY KEY,
    transaction_time FLOAT NOT NULL,
    v1 FLOAT NOT NULL,
    v2 FLOAT NOT NULL,
    v3 FLOAT NOT NULL,
    v4 FLOAT NOT NULL,
    v5 FLOAT NOT NULL,
    v6 FLOAT NOT NULL,
    v7 FLOAT NOT NULL,
    v8 FLOAT NOT NULL,
    v9 FLOAT NOT NULL,
    v10 FLOAT NOT NULL,
    v11 FLOAT NOT NULL,
    v12 FLOAT NOT NULL,
    v13 FLOAT NOT NULL,
    v14 FLOAT NOT NULL,
    v15 FLOAT NOT NULL,
    v16 FLOAT NOT NULL,
    v17 FLOAT NOT NULL,
    v18 FLOAT NOT NULL,
    v19 FLOAT NOT NULL,
    v20 FLOAT NOT NULL,
    v21 FLOAT NOT NULL,
    v22 FLOAT NOT NULL,
    v23 FLOAT NOT NULL,
    v24 FLOAT NOT NULL,
    v25 FLOAT NOT NULL,
    v26 FLOAT NOT NULL,
    v27 FLOAT NOT NULL,
    v28 FLOAT NOT NULL,
    amount FLOAT NOT NULL,
    class INT NOT NULL
);

CREATE TABLE "synthetic" (
    id SERIAL PRIMARY KEY,
    step INT NOT NULL,
    transaction_type VARCHAR(25) NOT NULL,
    amount FLOAT NOT NULL,
    name_origin VARCHAR(30),
    old_origin_balance FLOAT NOT NULL,
    new_origin_balance FLOAT NOT NULL,
    name_destination VARCHAR(30) NOT NULL,
    old_destination_balance FLOAT NOT NULL,
    new_destination_balane FLOAT NOT NULL,
    is_fraud INT NOT NULL,
    is_fraud_flagged INT NOT NULL
);